version: "3.7"
services:
  # Backend
  api:
    container_name: "archivica_api"
    build: .
    restart: always
    volumes:
      - ./src/:/app
    depends_on:
      - redis
      - mongodb
    environment:
      NODE_ENV: production
    ports:
      - "4000:4000"
  # Redis
  redis:
    image: 'redis:5.0.0'
    command: redis-server
    ports:
      - "6379:6379"
  # MongoDB
  mongodb:
    build: ./mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
volumes:
  mongodata: