version: "3.7"
services:
  # Postgres DB
  postgres:
    build:
      context: './postgres'
      target: dev
    volumes:
        - ./postgres/pgdata:/var/lib/postgresql
    ports:
        - "5432:5432"
  # Redis
  redis:
    image: 'redis:5.0.0'
    command: redis-server
    ports:
      - "6379:6379"
  # MongoDB
  mongodb:
    build: ./mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
volumes:
  mongodata: