export default {
	USER_REGISTER: "/api/v1/users/register",
	USER_LOGIN: "/api/v1/users/login",
	USER_LOGOUT: "/api/v1/users/logout",
	CURRENT_USER: "/api/v1/users/current",
	REFRESH_TOKEN: "/api/v1/users/refresh-token",
	VALIDATE_TOKEN: "/api/v1/users/validate-token",
	FORGOT_PASSWORD: "/api/v1/users/forgot-password",
	RESET_PASSWORD: "/api/v1/users/reset-password",
	POSTS: "/api/v1/posts",
	BLOGS: "/api/v1/blogs",
	HEALTH: "/api/v1/health",
	CODENAMES: "/api/v1/codenames",
	ARCHITECTS: "/api/v1/architects",
	COUNTRIES: "/api/v1/countries",
	CITIES: "/api/v1/cities",
	ARCHITECTURE_STYLES: "/api/v1/architecture-styles",
	ARCHITECTURE_PERIODS: "/api/v1/architecture-periods",
};